language: go
go:
    - "1.6"

addons:
    apt:
        packages:
            - libzmq3-dev

script:
    - cd $BUILD_DIR && go get ./...
    - go build
    - go test -v ./...

sudo: required
install:
    - export BUILD_DIR=$(pwd)
    - git clone git://github.com/jedisct1/libsodium.git && cd libsodium && git checkout stable && ./autogen.sh && ./configure && sudo make install && sudo ldconfig && cd ..
    - wget http://download.zeromq.org/zeromq-4.1.4.tar.gz && tar -xvf zeromq-4.1.4.tar.gz && cd zeromq-4.1.4 && ./autogen.sh && ./configure && sudo make install && sudo ldconfig && cd ..

notifications:
    email:
        on_success: change
        on_failure: always
