# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/en/latest/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/en/latest/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/en/latest/userguide/cmd_ci.html >
#
#
# Please choice one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


#
# Template #1: General project. Test it using existing `platformio.ini`.
#

language: go
go:
    - "1.6"

addons:
    apt:
        packages:
            - libzmq3-dev

script:
    - pwd
    - cd $GOPATH/src/github.com/rxwen/thrift-zmq-transport
    - pwd
    - go get ./...
    - go build
    - go test -v ./...

sudo: required
install:
    - pwd
    - git clone git://github.com/jedisct1/libsodium.git && cd libsodium && git checkout stable && ./autogen.sh && ./configure && make check && sudo make install && sudo ldconfig && cd ..
    - wget http://download.zeromq.org/zeromq-4.1.4.tar.gz && tar -xvf zeromq-4.1.4.tar.gz && cd zeromq-4.1.4 && ./autogen.sh && ./configure && make check && sudo make install && sudo ldconfig && cd ..

notifications:
    email:
        on_success: change
        on_failure: always
